plugins {
    id 'groovy'
    id 'org.grails.grails-web' version '5.0.0'
    id 'org.grails.grails-gsp' version '5.0.0'
    id 'org.grails.grails-plugin-rest-api' version '5.0.0'
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.19'
    implementation 'org.grails:grails-core:5.0.0'
    implementation 'org.grails:grails-plugin-rest:5.0.0'
    implementation 'org.grails:grails-plugin-services:5.0.0'
    implementation 'org.grails:grails-plugin-url-mappings:5.0.0'
    implementation 'org.grails:grails-plugin-gsp:5.0.0'
    implementation 'org.grails:grails-web-url-mappings:5.0.0'
    implementation 'org.grails:grails-testing-support:5.0.0'
    testImplementation 'org.grails:grails-plugin-testing:5.0.0'
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}