apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: build
    image:
    command:
    - sleep
    args:
    - 99d
    imagePullPolicy: Always
  - name: jnlp
    image: vmrm.aladdin.ru:4000/devops/build-images/jenkins-base-build-image:jenkins-agent-latest-jdk8
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  nodeSelector:
    kubernetes.io/os: "linux"
