plugins {
    id 'groovy'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.9'
    implementation 'org.codehaus.groovy:groovy-json:3.0.9'
    implementation 'org.codehaus.groovy:groovy-xml:3.0.9'
    implementation 'commons-io:commons-io:2.11.0'
}

mainClassName = 'JsonProcessor'